HKEY_DISPLAY_STRING_PATH = "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Screensavers\ssText3d"
DISPLAY_STRING_KEY = "DisplayString"
DISPLAY_STRING_VALUE = ""
ROTATION_SPEED_KEY = "RotationSpeed"
ROTATION_SPEED_VALUE = 1
ROTATION_STYLE_KEY = "RotationStyle"
ROTATION_STYLE_VALUE = 0
SIZE_KEY = "Size"
SIZE_VALUE = "a"
FONT_KEY = "FontFace"
FONT_VALUE = "Comic"
CUSTOM_COLOR_BOOL_KEY = "SurfaceType"
CUSTOM_COLOR_BOOL_VALUE = 1
CUSTOM_COLOR_KEY = "SurfaceColor"
CUSTOM_COLOR_VALUES = @("27ed01", "ed01ec", "ed8301", "017ced", "f1f400") #Green, Pink, Orange, Blue, Yellow

HKEY_SCREENSAVER_PATH = "HKEY_CURRENT_USER\Control Panel\Desktop"
SCREEN_SAVER_KEY = "SCRNSAVE.EXE"
SCREEN_SAVER_VALUE = "C:\Windows\System32\ssText3d.scr"
SCREEN_SAVE_ACTIVE_KEY = "ScreenSaveActive "
SCREEN_SAVE_ACTIVE_VALUE = 1
SCREEN_SAVE_TIMEOUT_KEY = "ScreenSaveTimeOut"
SCREEN_SAVE_TIMEOUT_VALUE = 60


